import InfoPageLayout from '@/layouts/InfoPageLayout';
import { motion } from 'framer-motion';
import { GradientHeading } from '@/components/ui/GradientHeading';
import { Description } from '@/components/ui/Description';

const MedicalDisclaimer = () => {
  const lastUpdated = "October 26, 2025";

  return (
    <InfoPageLayout>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto"
        >
          <GradientHeading as="h1" className="text-3xl md:text-5xl font-bold text-center mb-2">
            Medical Disclaimer
          </GradientHeading>
          <Description className="text-center text-brand-text-muted mb-12">Last updated: {lastUpdated}</Description>
          
          <div className="prose prose-lg max-w-none prose-h2:font-satoshi prose-h2:text-2xl prose-h2:md:text-3xl prose-h2:mb-6 prose-h2:pb-4 prose-h2:border-b prose-h2:border-brand-border prose-h3:text-xl prose-h3:md:text-2xl prose-h3:font-bold prose-h3:text-brand-text prose-a:text-brand-accent hover:prose-a:text-amber-700 prose-strong:text-brand-text">
            
            <div className="border-l-4 border-red-500 bg-red-500/10 p-6 rounded-r-lg my-8">
                <h2 className="!text-xl !font-bold !text-red-700 !border-none !pb-0 !mb-2">⚠️ IMPORTANT: READ CAREFULLY BEFORE USING GP GUIDE</h2>
            </div>

            <h2>EDUCATIONAL TOOL ONLY</h2>
            <p>GP Guide is an <strong>EDUCATIONAL SUBSCRIPTION SERVICE</strong> for registered health practitioners in Australia. GP Guide provides template generation tools and educational materials ONLY.</p>
            <p>GP Guide is NOT:</p>
            <ul>
                <li>A medical advice service</li>
                <li>A diagnostic tool</li>
                <li>A prescribing decision support system</li>
                <li>A substitute for clinical consultation</li>
                <li>A treatment recommendation service</li>
                <li>Emergency medical support</li>
            </ul>

            <h2>NO DOCTOR-PATIENT RELATIONSHIP</h2>
            <p>Use of GP Guide does NOT establish any doctor-patient, therapeutic, or clinical relationship between:</p>
            <ul>
                <li>GP Guide and any patient</li>
                <li>GP Guide staff/contractors and any patient</li>
                <li>New Era Pty Ltd and any patient</li>
            </ul>
            <p>GP Guide does not provide medical advice, diagnosis, or treatment.</p>

            <h2>NO SUBSTITUTE FOR CLINICAL ASSESSMENT</h2>
            <p>GP Guide outputs are NOT a substitute for:</p>
            <ul>
                <li>Real-time clinical consultation</li>
                <li>Independent patient assessment and examination</li>
                <li>Professional clinical judgment</li>
                <li>Contemporaneous evaluation of patient condition</li>
                <li>Direct patient-practitioner interaction</li>
            </ul>
            <p>Templates generated by GP Guide are <strong>DRAFT EDUCATIONAL MATERIALS</strong> only.</p>

            <h2>USER RESPONSIBILITY</h2>
            <p>As a registered health practitioner using GP Guide, <strong>YOU</strong> are solely responsible for:</p>
            <ul>
                <li>✓ All clinical decisions</li>
                <li>✓ Patient assessment and diagnosis</li>
                <li>✓ Treatment planning and prescribing</li>
                <li>✓ Verifying all template content before clinical use</li>
                <li>✓ Customizing templates for individual patients</li>
                <li>✓ Checking current guidelines (RACGP, MBS, PBS, eTG)</li>
                <li>✓ Ensuring clinical appropriateness</li>
                <li>✓ Compliance with professional standards</li>
                <li>✓ Maintaining professional indemnity insurance</li>
            </ul>
            <p>GP Guide accepts NO responsibility for:</p>
            <ul>
                <li>✗ Clinical decisions or patient outcomes</li>
                <li>✗ Errors or omissions in templates</li>
                <li>✗ Outdated guideline references</li>
                <li>✗ Inappropriate use of templates</li>
                <li>✗ Adverse patient events</li>
            </ul>

            <h2>VERIFY ALL INFORMATION</h2>
            <p>You MUST independently verify:</p>
            <ul>
                <li>Clinical accuracy of all template content</li>
                <li>Currency of guideline references</li>
                <li>MBS item eligibility and requirements</li>
                <li>PBS prescribing criteria</li>
                <li>RACGP Red Book recommendations</li>
                <li>Therapeutic Guidelines (eTG) updates</li>
                <li>Specialist college guidelines</li>
            </ul>
            <p>Medical guidelines change frequently. GP Guide does NOT guarantee real-time updates or current information.</p>

            <h2>NO CLINICAL ACCURACY GUARANTEE</h2>
            <p>GP Guide makes NO representations or warranties regarding:</p>
            <ul>
                <li>Clinical accuracy of templates</li>
                <li>Completeness of information</li>
                <li>Currency of guideline references</li>
                <li>Suitability for specific clinical situations</li>
                <li>Compliance with current standards</li>
            </ul>
            <p>Templates are based on guidelines current as of our last review date. Verification against current sources is MANDATORY.</p>

            <h2>GUIDELINE REFERENCES</h2>
            <p>GP Guide templates reference publicly available Australian medical guidelines including:</p>
            <ul>
                <li>Royal Australian College of General Practitioners (RACGP) guidelines</li>
                <li>Therapeutic Guidelines (eTG)</li>
                <li>Medicare Benefits Schedule (MBS) item descriptors</li>
                <li>Pharmaceutical Benefits Scheme (PBS) criteria</li>
            </ul>
            <p>GP Guide is NOT:</p>
            <ul>
                <li>Endorsed by these organizations</li>
                <li>Certified or approved by these organizations</li>
                <li>Affiliated with these organizations</li>
                <li>Claiming official endorsement</li>
            </ul>
            <p>References to guidelines are for educational purposes only and do not constitute compliance certification.</p>

            <h2>NOT FOR EMERGENCY USE</h2>
            <div className="border-l-4 border-red-500 bg-red-500/10 p-4 rounded-r-lg my-6">
                <p className="!my-0 text-red-700">⚠️ DO NOT use GP Guide for emergency medical situations.</p>
            </div>
            <p>For emergencies:</p>
            <ul>
                <li>Call 000 (Australia)</li>
                <li>Go to nearest emergency department</li>
                <li>Seek immediate in-person medical care</li>
            </ul>
            <p>GP Guide provides documentation tools only and cannot assist with urgent clinical matters.</p>

            <h2>NOT FOR PRESCRIBING WITHOUT ASSESSMENT</h2>
            <p>GP Guide does NOT support:</p>
            <ul>
                <li>Prescribing without real-time patient consultation</li>
                <li>Asynchronous prescribing based on questionnaires alone</li>
                <li>Automated prescribing decisions</li>
                <li>Medication recommendations without clinical assessment</li>
            </ul>
            <p>Per Medical Board of Australia telehealth guidelines:</p>
            <ul>
                <li>Prescribing requires adequate clinical assessment</li>
                <li>Real-time consultation is required for new prescriptions</li>
                <li>Questionnaires alone are insufficient for prescribing</li>
                <li>Clinical responsibility remains with practitioner</li>
            </ul>

            <h2>PROFESSIONAL STANDARDS COMPLIANCE</h2>
            <p>Use of GP Guide does NOT exempt you from:</p>
            <ul>
                <li>Medical Board of Australia requirements</li>
                <li>AHPRA registration obligations</li>
                <li>Professional college standards</li>
                <li>State/territory medical practice laws</li>
                <li>Privacy Act 1988 (Cth) compliance</li>
                <li>Australian Privacy Principles compliance</li>
            </ul>
            <p>You remain subject to all professional obligations and standards.</p>

            <h2>PATIENT DATA PROTECTION</h2>
            <div className="border-l-4 border-amber-500 bg-amber-500/10 p-4 rounded-r-lg my-6">
                <p className="!my-0 text-amber-700">⚠️ DO NOT ENTER PATIENT-IDENTIFIABLE INFORMATION</p>
            </div>
            <p>GP Guide is designed for minimal data input. You should NOT enter:</p>
            <ul>
                <li>Patient names</li>
                <li>Medicare numbers</li>
                <li>Addresses</li>
                <li>Dates of birth</li>
                <li>Phone numbers</li>
                <li>Email addresses</li>
                <li>Other personal identifiers</li>
            </ul>
            <p>Enter ONLY:</p>
            <ul>
                <li>Generic clinical details necessary for template generation</li>
                <li>De-identified information</li>
                <li>Clinical descriptors without identifiers</li>
            </ul>
            <p>YOU are responsible for:</p>
            <ul>
                <li>Ensuring no identifiable patient data is submitted</li>
                <li>Compliance with Privacy Act 1988 (Cth)</li>
                <li>Protection of patient confidentiality</li>
                <li>Secure handling of generated templates</li>
            </ul>

            <h2>LIMITATION OF LIABILITY</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY AUSTRALIAN LAW:</p>
            <p>GP Guide and New Era Pty Ltd are NOT liable for:</p>
            <ul>
                <li>Clinical decisions or patient outcomes</li>
                <li>Patient harm or adverse events</li>
                <li>Errors, omissions, or inaccuracies in templates</li>
                <li>Outdated guideline information</li>
                <li>Inappropriate use of templates</li>
                <li>Reliance on template content without verification</li>
                <li>Any direct, indirect, consequential, or special damages</li>
            </ul>
            <p>Your use of GP Guide is at your own risk.</p>

            <h2>PROFESSIONAL INDEMNITY INSURANCE REQUIRED</h2>
            <p>GP Guide users MUST maintain:</p>
            <ul>
                <li>Current professional indemnity insurance</li>
                <li>Coverage appropriate for their scope of practice</li>
                <li>Insurance covering use of documentation tools</li>
            </ul>
            <p>GP Guide does NOT provide professional indemnity coverage for users.</p>

            <h2>STATE AND TERRITORY VARIATIONS</h2>
            <p>Australian medical practice requirements may vary by state/territory. You are responsible for:</p>
            <ul>
                <li>Knowing applicable state/territory requirements</li>
                <li>Complying with local regulations</li>
                <li>Verifying WorkCover/WorkSafe requirements (for workers compensation templates)</li>
                <li>Checking Centrelink requirements (for SU415 forms)</li>
            </ul>
            <p>GP Guide templates may require modification for state-specific requirements.</p>

            <h2>UPDATES AND REVISIONS</h2>
            <p>GP Guide templates are reviewed and updated periodically, but we do NOT guarantee:</p>
            <ul>
                <li>Real-time updates when guidelines change</li>
                <li>Notification of guideline revisions</li>
                <li>That templates reflect the most current information</li>
            </ul>
            <p>Last template review: {lastUpdated}</p>
            <p>Next scheduled review: January 2026</p>
            <p>Check with current guideline sources before clinical use.</p>

            <h2>THIRD-PARTY LINKS AND REFERENCES</h2>
            <p>GP Guide may include links to third-party websites (RACGP, eTG, PBS, etc.) for reference purposes. We are NOT responsible for:</p>
            <ul>
                <li>Content of third-party sites</li>
                <li>Accuracy of external information</li>
                <li>Availability of external links</li>
                <li>Privacy practices of third-party sites</li>
            </ul>

            <h2>NO GUARANTEE OF SUITABILITY</h2>
            <p>GP Guide makes NO guarantee that templates are suitable for:</p>
            <ul>
                <li>Your specific clinical practice</li>
                <li>Individual patient situations</li>
                <li>Your scope of practice</li>
                <li>Your specialty or subspecialty</li>
                <li>Specific regulatory requirements in your jurisdiction</li>
            </ul>
            <p>Templates are general educational resources only.</p>

            <h2>ACKNOWLEDGMENT OF RISK</h2>
            <p>By using GP Guide, you acknowledge and accept that:</p>
            <ul>
                <li>Templates are educational drafts requiring review and customization</li>
                <li>You bear full responsibility for clinical decisions</li>
                <li>You will verify all content independently</li>
                <li>You understand the limitations of GP Guide</li>
                <li>You will use templates only as starting points, not final documents</li>
                <li>You accept all risks associated with use of the Service</li>
            </ul>

            <h2>CONSULTATION WITH PATIENTS</h2>
            <p>All clinical decisions must be based on:</p>
            <ul>
                <li>Real-time consultation with the patient</li>
                <li>Physical examination where appropriate</li>
                <li>Review of current patient records</li>
                <li>Patient history and context</li>
                <li>Your professional clinical judgment</li>
                <li>Current evidence-based guidelines</li>
            </ul>
            <p>GP Guide outputs must NOT be used without proper patient consultation and assessment.</p>

            <h2>SPECIAL POPULATIONS</h2>
            <p>Exercise extra caution when using templates for:</p>
            <ul>
                <li>Pediatric patients</li>
                <li>Elderly patients</li>
                <li>Pregnant or breastfeeding patients</li>
                <li>Patients with complex medical conditions</li>
                <li>Patients with multiple comorbidities</li>
                <li>Aboriginal and Torres Strait Islander patients</li>
                <li>Culturally and linguistically diverse patients</li>
            </ul>
            <p>Templates may require significant customization for special populations.</p>

            <h2>MEDICATION SAFETY</h2>
            <p>GP Guide does NOT provide:</p>
            <ul>
                <li>Medication dosing calculators</li>
                <li>Drug interaction checking</li>
                <li>Contraindication screening</li>
                <li>Prescribing decision support</li>
            </ul>
            <p>Always verify:</p>
            <ul>
                <li>Current PBS criteria</li>
                <li>eTG prescribing recommendations</li>
                <li>Drug interactions and contraindications</li>
                <li>Patient-specific factors</li>
                <li>Renal/hepatic dose adjustments</li>
            </ul>
            <p>Use appropriate clinical decision support tools for prescribing.</p>

            <h2>MENTAL HEALTH CONSIDERATIONS</h2>
            <p>Mental health plan templates are educational only. You must:</p>
            <ul>
                <li>Conduct thorough mental health assessment</li>
                <li>Assess suicide risk independently</li>
                <li>Ensure appropriate safety planning</li>
                <li>Provide crisis resources</li>
                <li>Follow up appropriately</li>
                <li>Comply with mental health legislation</li>
            </ul>
            <p>GP Guide templates do NOT replace comprehensive mental health assessment.</p>

            <h2>QUALITY IMPROVEMENT</h2>
            <p>While we strive for accuracy, GP Guide cannot guarantee error-free content. If you identify errors or outdated information:</p>
            <p>Email: <a href="mailto:support@gpguide.com.au">support@gpguide.com.au</a></p>
            <p>Subject: Template Error Report</p>
            <p>Include:</p>
            <ul>
                <li>Specific template and section</li>
                <li>Description of error</li>
                <li>Reference to correct information</li>
                <li>Your suggestions for improvement</li>
            </ul>
            <p>We review all error reports and update templates accordingly.</p>

            <h2>LEGAL AND REGULATORY CHANGES</h2>
            <p>Australian medical practice laws and regulations change frequently. GP Guide templates may not reflect:</p>
            <ul>
                <li>Recent legislative changes</li>
                <li>New MBS items or criteria</li>
                <li>Updated PBS restrictions</li>
                <li>Revised professional standards</li>
                <li>Changes to state/territory requirements</li>
            </ul>
            <p>You are responsible for staying current with regulatory changes.</p>

            <h2>INFORMED CONSENT</h2>
            <p>Ensure you obtain proper informed consent from patients before:</p>
            <ul>
                <li>Implementing any treatment plan</li>
                <li>Prescribing medications</li>
                <li>Performing procedures</li>
                <li>Making referrals</li>
            </ul>
            <p>GP Guide templates do NOT replace proper informed consent processes.</p>

            <h2>CONTINUING PROFESSIONAL DEVELOPMENT</h2>
            <p>GP Guide is a documentation tool and does NOT provide:</p>
            <ul>
                <li>CPD points or credits</li>
                <li>Professional education courses</li>
                <li>Clinical training</li>
                <li>Formal medical education</li>
            </ul>
            <p>Use of GP Guide does not fulfill CPD requirements.</p>

            <h2>CONTACT FOR CLINICAL QUESTIONS</h2>
            <p>GP Guide does NOT provide clinical advice or support.</p>
            <p>For clinical questions:</p>
            <ul>
                <li>Consult current guidelines (RACGP, eTG, PBS)</li>
                <li>Contact relevant specialist colleges</li>
                <li>Seek peer consultation</li>
                <li>Access clinical decision support services</li>
                <li>Contact HealthDirect or NPS MedicineWise</li>
            </ul>
            <p>For GP Guide technical support only:</p>
            <p>Email: <a href="mailto:support@gpguide.com.au">support@gpguide.com.au</a></p>

            <h2>ACCEPTANCE OF DISCLAIMER</h2>
            <p>By using GP Guide, you acknowledge that you have:</p>
            <ul>
                <li>Read and understood this Medical Disclaimer</li>
                <li>Agreed to use GP Guide as an educational tool only</li>
                <li>Accepted full clinical responsibility for patient care</li>
                <li>Agreed to verify all template content independently</li>
                <li>Understood the limitations of GP Guide</li>
                <li>Confirmed you will not rely on GP Guide for clinical decision-making</li>
            </ul>

            <h2>DISCLAIMER UPDATES</h2>
            <p>This Medical Disclaimer may be updated periodically. Continued use of GP Guide constitutes acceptance of the current version.</p>
            <p>Last updated: {lastUpdated}</p>

            <hr />

            <p>© 2025 New Era Pty Ltd (trading as GP Guide). All rights reserved.</p>
            <p>⚠️ This disclaimer is a critical legal document. Always read it carefully before using GP Guide.</p>
          </div>
        </motion.div>
      </div>
    </InfoPageLayout>
  );
};

export default MedicalDisclaimer;
