import InfoPageLayout from '@/layouts/InfoPageLayout';
import { motion } from 'framer-motion';
import { GradientHeading } from '@/components/ui/GradientHeading';
import { Description } from '@/components/ui/Description';

const TermsOfService = () => {
  const lastUpdated = "October 26, 2025";

  return (
    <InfoPageLayout>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 md:py-24">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto"
        >
          <GradientHeading as="h1" className="text-3xl md:text-5xl font-bold text-center mb-2">
            Terms of Service
          </GradientHeading>
          <Description className="text-center text-brand-text-muted mb-12">Last updated: {lastUpdated}</Description>
          
          <div className="prose prose-lg max-w-none prose-h2:font-satoshi prose-h2:text-2xl prose-h2:md:text-3xl prose-h2:mb-6 prose-h2:pb-4 prose-h2:border-b prose-h2:border-brand-border prose-h3:text-xl prose-h3:md:text-2xl prose-h3:font-bold prose-h3:text-brand-text prose-a:text-brand-accent hover:prose-a:text-amber-700 prose-strong:text-brand-text">
            <p>These Terms of Service ("Terms") govern your use of GP Guide, operated by New Era Pty Ltd (ABN: 14 345 878 901) ("we," "us," "our"). By subscribing to or using GP Guide, you agree to these Terms.</p>
            <hr />
            <h2>1. DEFINITIONS</h2>
            <p><strong>"GP Guide" or "Service":</strong> The educational subscription platform providing clinical template generation tools.</p>
            <p><strong>"User," "you," "your":</strong> A registered health practitioner subscribing to and using GP Guide.</p>
            <p><strong>"Templates":</strong> Educational draft documents generated by GP Guide tools.</p>
            <p><strong>"Content":</strong> All materials, information, templates, and resources provided by GP Guide.</p>
            <hr />
            <h2>2. SERVICE PURPOSE</h2>
            <p>GP Guide is an educational subscription service designed for registered health practitioners in Australia. The Service provides:</p>
            <ul>
                <li>Template generation tools</li>
                <li>Educational materials</li>
                <li>Documentation assistance</li>
            </ul>
            <p>GP Guide is <strong>NOT</strong>:</p>
            <ul>
                <li>A substitute for clinical assessment</li>
                <li>A diagnostic tool</li>
                <li>A prescribing decision support system</li>
                <li>Emergency medical support</li>
                <li>A replacement for professional judgment</li>
            </ul>
            <hr />
            <h2>3. ELIGIBILITY AND USER OBLIGATIONS</h2>
            <h3>3.1 Eligibility</h3>
            <p>You warrant that you are:</p>
            <ul>
                <li>A registered health practitioner in Australia (AHPRA-registered or equivalent)</li>
                <li>Legally authorized to practice in your profession</li>
                <li>Using the Service for professional purposes only</li>
                <li>At least 18 years of age</li>
            </ul>
            <h3>3.2 Registration Verification</h3>
            <p>We may verify your AHPRA registration or professional credentials. Providing false information is grounds for immediate account termination without refund.</p>
            <h3>3.3 Account Security</h3>
            <p>You are responsible for:</p>
            <ul>
                <li>Maintaining confidentiality of your login credentials</li>
                <li>All activity under your account</li>
                <li>Notifying us immediately of unauthorized access</li>
                <li>Using strong passwords and security practices</li>
            </ul>
            <p>Do <strong>NOT</strong> share your account with others.</p>
            <hr />
            <h2>4. USER RESPONSIBILITIES</h2>
            <h3>4.1 Clinical Responsibility</h3>
            <p>You acknowledge and agree that:</p>
            <ul>
                <li><strong>YOU</strong> are solely responsible for all clinical decisions</li>
                <li><strong>YOU</strong> must verify all template content before clinical use</li>
                <li><strong>YOU</strong> must perform independent patient assessment</li>
                <li><strong>YOU</strong> must check current guidelines (RACGP, MBS, PBS, eTG) before use</li>
                <li>Templates are educational drafts only</li>
                <li>GP Guide does not establish a doctor-patient relationship</li>
            </ul>
            <h3>4.2 Patient Data Protection</h3>
            <p>You agree to:</p>
            <ul>
                <li><strong>NOT</strong> enter patient-identifiable information (names, Medicare numbers, addresses, DOB, etc.)</li>
                <li>Enter only generic clinical details necessary for template generation</li>
                <li>Comply with Privacy Act 1988 (Cth) and Australian Privacy Principles</li>
                <li>Take sole responsibility for any patient data you choose to enter</li>
            </ul>
            <h3>4.3 Professional Standards</h3>
            <p>You agree to:</p>
            <ul>
                <li>Use GP Guide in accordance with your professional obligations</li>
                <li>Comply with Medical Board of Australia guidelines</li>
                <li>Maintain appropriate professional indemnity insurance</li>
                <li>Use templates only within your scope of practice</li>
            </ul>
            <hr />
            <h2>5. NO CLINICAL RELATIONSHIP</h2>
            <p>Use of GP Guide does not establish any doctor-patient, therapeutic, or clinical relationship between:</p>
            <ul>
                <li>GP Guide and any patient</li>
                <li>GP Guide and you (the user)</li>
                <li>GP Guide staff/contractors and any patient</li>
            </ul>
            <p>GP Guide does not provide medical advice, diagnosis, treatment, or prescribing recommendations.</p>
            <hr />
            <h2>6. NO SUBSTITUTE FOR CLINICAL ASSESSMENT</h2>
            <p>GP Guide outputs are NOT a substitute for:</p>
            <ul>
                <li>Contemporaneous clinical consultation</li>
                <li>Independent patient assessment</li>
                <li>Real-time clinical examination</li>
                <li>Professional clinical judgment</li>
                <li>Current guideline verification</li>
            </ul>
            <p>Always verify template content against current RACGP, MBS, PBS, and eTG guidelines before clinical use.</p>
            <hr />
            <h2>7. SUBSCRIPTIONS AND BILLING</h2>
            <h3>7.1 Plans Available</h3>
            <ul>
                <li>Basic Plan: $19.99 AUD/week (regular price)</li>
                <li>Professional Plan: $29.99 AUD/week (regular price)</li>
                <li>Promotional pricing may be offered at our discretion</li>
            </ul>
            <h3>7.2 Billing</h3>
            <ul>
                <li>Subscriptions are billed weekly in advance</li>
                <li>Payment is charged automatically to your payment method every 7 days</li>
                <li>Billing continues until you cancel</li>
                <li>You must maintain valid payment method on file</li>
            </ul>
            <h3>7.3 Price Changes</h3>
            <p>We reserve the right to change pricing with 30 days' notice. Existing subscribers will be notified by email before any price increase takes effect.</p>
            <h3>7.4 Taxes</h3>
            <p>Prices include GST where applicable. You are responsible for any additional taxes based on your location.</p>
            <h3>7.5 Failed Payments</h3>
            <p>If payment fails:</p>
            <ul>
                <li>We will attempt to re-charge within 3 days</li>
                <li>You will be notified by email</li>
                <li>Access may be suspended until payment succeeds</li>
                <li>After 7 days of failed payment, account may be terminated</li>
            </ul>
            <hr />
            <h2>8. CANCELLATION AND REFUNDS</h2>
            <h3>8.1 Cancellation</h3>
            <p>You may cancel anytime:</p>
            <ol>
                <li>Log into your account</li>
                <li>Go to Account Settings &gt; Subscription</li>
                <li>Click "Cancel Subscription"</li>
                <li>Access continues until end of current billing period</li>
                <li>No refund for unused portion of current period</li>
            </ol>
            <p>No cancellation fees apply.</p>
            <h3>8.2 Refunds</h3>
            <p>See our <a href="/refund-policy">Refund Policy</a> page for full details. Generally:</p>
            <ul>
                <li>No refunds during promotional pricing period</li>
                <li>Regular pricing: Pro-rata refunds may be available in limited circumstances</li>
                <li>Refund requests must be submitted within 7 days of charge</li>
                <li>Contact <a href="mailto:support@gpguide.com.au">support@gpguide.com.au</a> for refund requests</li>
            </ul>
            <h3>8.3 Our Right to Terminate</h3>
            <p>We may suspend or terminate your account immediately for:</p>
            <ul>
                <li>Breach of these Terms</li>
                <li>Fraudulent activity</li>
                <li>Providing false registration information</li>
                <li>Misuse of the Service</li>
                <li>Non-payment</li>
                <li>Violation of Australian law or professional standards</li>
            </ul>
            <p>Termination for breach: No refund provided.</p>
            <hr />
            <h2>9. INTELLECTUAL PROPERTY</h2>
            <h3>9.1 GP Guide Content</h3>
            <p>All content, templates, software, design, trademarks, and materials are owned by New Era Pty Ltd or our licensors and protected by:</p>
            <ul>
                <li>Australian copyright law (Copyright Act 1968)</li>
                <li>Trademark law</li>
                <li>Intellectual property laws</li>
            </ul>
            <h3>9.2 Your License</h3>
            <p>We grant you a limited, non-exclusive, non-transferable license to:</p>
            <ul>
                <li>Access and use GP Guide during your active subscription</li>
                <li>Generate templates for your clinical practice</li>
                <li>Export templates for use in patient records</li>
            </ul>
            <p>You may <strong>NOT</strong>:</p>
            <ul>
                <li>Resell, redistribute, or commercially exploit GP Guide content</li>
                <li>Reverse engineer or copy our software</li>
                <li>Remove copyright or proprietary notices</li>
                <li>Share your account or login credentials</li>
                <li>Use templates outside your clinical practice without permission</li>
            </ul>
            <h3>9.3 Template Outputs</h3>
            <p>Templates you generate may be used in your clinical practice. However:</p>
            <ul>
                <li>You must review and customize all templates before use</li>
                <li>GP Guide retains no rights to your patient records</li>
                <li>You own the final customized documents you create</li>
            </ul>
            <hr />
            <h2>10. DISCLAIMER OF WARRANTIES</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
            <p>GP Guide is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, express or implied, including but not limited to:</p>
            <ul>
                <li>Accuracy or completeness of templates</li>
                <li>Fitness for a particular purpose</li>
                <li>Non-infringement</li>
                <li>Uninterrupted or error-free service</li>
                <li>Security of data transmission</li>
                <li>Currency of clinical guidelines</li>
            </ul>
            <p>We do <strong>NOT</strong> warrant that:</p>
            <ul>
                <li>Templates are clinically accurate</li>
                <li>Content reflects current guidelines</li>
                <li>Service will meet your requirements</li>
                <li>Service will be available at all times</li>
            </ul>
            <hr />
            <h2>11. LIMITATION OF LIABILITY</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY AUSTRALIAN LAW:</p>
            <h3>11.1 Exclusion of Liability</h3>
            <p>GP Guide and New Era Pty Ltd are <strong>NOT</strong> liable for any:</p>
            <ul>
                <li>Clinical decisions or outcomes</li>
                <li>Patient harm or adverse events</li>
                <li>Errors or inaccuracies in templates</li>
                <li>Loss of data or information</li>
                <li>Service interruptions or downtime</li>
                <li>Indirect, consequential, or special damages</li>
                <li>Loss of profits, revenue, or business opportunities</li>
            </ul>
            <h3>11.2 Maximum Liability</h3>
            <p>Our total liability to you for any claim arising from use of GP Guide is limited to the amount you paid for the Service in the 3 months prior to the claim.</p>
            <h3>11.3 Australian Consumer Law</h3>
            <p>Nothing in these Terms excludes, restricts, or modifies any consumer rights under the Australian Consumer Law (Competition and Consumer Act 2010) that cannot be excluded.</p>
            <p>Where we are liable under Australian Consumer Law, our liability is limited to (at our option):</p>
            <ul>
                <li>Re-supplying the Service</li>
                <li>Refunding the subscription fee</li>
            </ul>
            <hr />
            <h2>12. INDEMNITY</h2>
            <p>You agree to indemnify and hold harmless New Era Pty Ltd, its directors, employees, contractors, and agents from all claims, damages, losses, liabilities, and expenses (including legal fees) arising from:</p>
            <ul>
                <li>Your use of GP Guide</li>
                <li>Your clinical decisions and patient care</li>
                <li>Incorporation of templates into patient records without appropriate review</li>
                <li>Breach of these Terms</li>
                <li>Violation of any law or professional standard</li>
                <li>Infringement of third-party rights</li>
            </ul>
            <hr />
            <h2>13. CLINICAL ACCURACY AND GUIDELINE CURRENCY</h2>
            <h3>13.1 No Guarantee of Accuracy</h3>
            <p>We do <strong>NOT</strong> guarantee:</p>
            <ul>
                <li>Clinical accuracy of templates</li>
                <li>Currency of guideline references</li>
                <li>Suitability for specific clinical situations</li>
                <li>Compliance with current MBS/PBS/RACGP standards</li>
            </ul>
            <h3>13.2 User Verification Required</h3>
            <p>You <strong>MUST</strong>:</p>
            <ul>
                <li>Independently verify all template content</li>
                <li>Check against current clinical guidelines</li>
                <li>Customize templates for individual patients</li>
                <li>Use your professional clinical judgment</li>
            </ul>
            <h3>13.3 Updates</h3>
            <p>We update templates periodically but do <strong>NOT</strong> guarantee:</p>
            <ul>
                <li>Real-time updates</li>
                <li>Notification of guideline changes</li>
                <li>That templates reflect the most current information</li>
            </ul>
            <hr />
            <h2>14. DATA AND PRIVACY</h2>
            <h3>14.1 Privacy Policy</h3>
            <p>Your use of GP Guide is also governed by our <a href="/privacy-policy">Privacy Policy</a>, which is incorporated into these Terms by reference.</p>
            <h3>14.2 Data Storage</h3>
            <ul>
                <li>We do <strong>NOT</strong> store patient-identifiable information</li>
                <li>Clinical input is processed in real-time only</li>
                <li>You are responsible for any data you choose to enter</li>
                <li>Exported templates are saved locally on your device</li>
            </ul>
            <h3>14.3 Backup</h3>
            <p>We do <strong>NOT</strong> provide backup of your generated templates. You are responsible for saving and backing up your own documents.</p>
            <hr />
            <h2>15. MEDICAL BOARD AND AHPRA COMPLIANCE</h2>
            <h3>15.1 Telehealth Guidelines</h3>
            <p>GP Guide is designed as a documentation tool only and complies with Medical Board of Australia telehealth guidelines by:</p>
            <ul>
                <li><strong>NOT</strong> providing prescribing recommendations without clinical assessment</li>
                <li><strong>NOT</strong> supporting asynchronous prescribing or questionnaire-only consultations</li>
                <li>Requiring clinician review of all outputs</li>
                <li>Being used as adjunct to clinical consultation, not replacement</li>
            </ul>
            <h3>15.2 Professional Obligations</h3>
            <p>You remain subject to:</p>
            <ul>
                <li>Medical Board of Australia guidelines</li>
                <li>AHPRA requirements</li>
                <li>Your professional registration conditions</li>
                <li>Relevant professional college standards</li>
            </ul>
            <hr />
            <h2>16. PROHIBITED USES</h2>
            <p>You may <strong>NOT</strong> use GP Guide for:</p>
            <ul>
                <li>Emergency medical situations</li>
                <li>Prescribing decisions without clinical assessment</li>
                <li>Diagnosis without patient examination</li>
                <li>Automated clinical decision-making</li>
                <li>Providing medical advice to patients based solely on templates</li>
                <li>Any illegal purpose</li>
                <li>Sharing or reselling access</li>
                <li>Circumventing security measures</li>
                <li>Introducing viruses or malicious code</li>
            </ul>
            <hr />
            <h2>17. FORCE MAJEURE</h2>
            <p>We are not liable for service interruptions due to circumstances beyond our reasonable control, including:</p>
            <ul>
                <li>Internet outages</li>
                <li>Server failures</li>
                <li>Natural disasters</li>
                <li>Cyber attacks</li>
                <li>Government actions</li>
                <li>Pandemics</li>
                <li>Third-party service failures</li>
            </ul>
            <hr />
            <h2>18. UPDATES AND NEW FEATURES</h2>
            <h3>18.1 Service Updates</h3>
            <p>We may:</p>
            <ul>
                <li>Add new tools and features</li>
                <li>Modify existing features</li>
                <li>Update templates and content</li>
                <li>Change Service design or functionality</li>
            </ul>
            <h3>18.2 No Obligation</h3>
            <p>We have <strong>NO</strong> obligation to:</p>
            <ul>
                <li>Maintain any specific feature</li>
                <li>Provide advance notice of changes (except pricing)</li>
                <li>Support outdated versions</li>
            </ul>
            <hr />
            <h2>19. DISPUTE RESOLUTION</h2>
            <h3>19.1 Governing Law</h3>
            <p>These Terms are governed by the laws of Western Australia and the Commonwealth of Australia.</p>
            <h3>19.2 Jurisdiction</h3>
            <p>You agree to the exclusive jurisdiction of the courts of Western Australia for any disputes arising from these Terms or use of GP Guide.</p>
            <h3>19.3 Negotiation First</h3>
            <p>Before commencing legal proceedings, parties agree to attempt resolution through:</p>
            <ol>
                <li>Direct negotiation in good faith</li>
                <li>Mediation (if negotiation fails)</li>
                <li>Legal proceedings (as last resort)</li>
            </ol>
            <hr />
            <h2>20. SEVERABILITY</h2>
            <p>If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions remain in full force and effect.</p>
            <hr />
            <h2>21. ENTIRE AGREEMENT</h2>
            <p>These Terms, together with our Privacy Policy, Refund Policy, and Medical Disclaimer, constitute the entire agreement between you and GP Guide regarding use of the Service.</p>
            <hr />
            <h2>22. WAIVER</h2>
            <p>Our failure to enforce any provision of these Terms does not constitute a waiver of that provision or our right to enforce it in the future.</p>
            <hr />
            <h2>23. ASSIGNMENT</h2>
            <p>You may <strong>NOT</strong> assign or transfer your rights under these Terms. We may assign our rights and obligations to any successor entity (e.g., in event of merger or acquisition).</p>
            <hr />
            <h2>24. NOTICES</h2>
            <p>Notices to you will be sent via:</p>
            <ul>
                <li>Email to your registered account email</li>
                <li>Posting on the GP Guide website</li>
            </ul>
            <p>Notices are deemed received 24 hours after sending.</p>
            <p>To contact us:</p>
            <p>Email: <a href="mailto:support@gpguide.com.au">support@gpguide.com.au</a></p>
            <hr />
            <h2>25. SURVIVAL</h2>
            <p>Provisions that by their nature should survive termination (including indemnity, limitation of liability, intellectual property, and dispute resolution) will survive termination of these Terms.</p>
            <hr />
            <h2>26. ACKNOWLEDGMENT</h2>
            <p>By subscribing to GP Guide, you acknowledge that you have:</p>
            <ul>
                <li>Read and understood these Terms</li>
                <li>Read and understood the <a href="/privacy-policy">Privacy Policy</a></li>
                <li>Read and understood the <a href="/medical-disclaimer">Medical Disclaimer</a></li>
                <li>Agreed to be bound by all terms and conditions</li>
                <li>Confirmed you are a registered health practitioner</li>
            </ul>
            <hr />
            <p><strong>CONTACT INFORMATION</strong></p>
            <p>New Era Pty Ltd (trading as GP Guide)<br />
            ABN: 14 345 878 901<br />
            Email: <a href="mailto:support@gpguide.com.au">support@gpguide.com.au</a><br />
            Sydney, Australia</p>
            <hr />
            <p>© 2025 New Era Pty Ltd. All rights reserved.</p>
          </div>
        </motion.div>
      </div>
    </InfoPageLayout>
  );
};

export default TermsOfService;
